const BOARD_ACTIONS = {
    SET_STATE: "SET_STATE",
    SET_CARD: "SET_CARD",

    SET_LISTS: "SET_LISTS",
    SET_LIST_CARDS: "SET_LIST_CARDS",
    SET_CARDS: "SET_CARDS",

    UPDATE_BOARD_FIELD: "UPDATE_BOARD_FIELD",

    UPDATE_LIST_FIELD: "UPDATE_LIST_FIELD",
    ADD_LIST_TO_BOARD: "ADD_LIST_TO_BOARD",
    ADD_LIST_TO_BOARD_BY_INDEX: "ADD_LIST_TO_BOARD_INDEX",
    COPY_LIST: "COPY_LIST",
    DELETE_LIST: "DELETE_LIST",
    MOVE_LIST: "MOVE_LIST",

    UPDATE_CARD_FIELD: "UPDATE_CARD_FIELD",
    ADD_CARD: "ADD_CARD",
    DELETE_CARD: "DELETE_CARD",

    ADD_MEMBER: "ADD_MEMBER",
    REMOVE_MEMBER: "REMOVE_MEMBER",
};

export { BOARD_ACTIONS };
